"""Immutable migration 1: normalize the known legacy schema and bind request hashes.

Do not edit this file after publication. Add a new migration for future changes;
its source bytes are the checksum stored in the migration ledger.
"""

SCHEMA = """
CREATE TABLE IF NOT EXISTS tasks (
    id TEXT PRIMARY KEY,
    prompt TEXT NOT NULL,
    cwd TEXT,
    model TEXT,
    provider TEXT,
    session_id TEXT,
    profile TEXT,
    approval_mode TEXT NOT NULL DEFAULT 'approve' CHECK(approval_mode IN ('auto','approve','plan')),
    chat_only INTEGER NOT NULL DEFAULT 0,
    skills_json TEXT NOT NULL DEFAULT '[]',
    status TEXT NOT NULL CHECK(status IN ('queued','running','completed','failed','cancelled','blocked')),
    result_json TEXT,
    error TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    started_at TEXT,
    completed_at TEXT,
    retry_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_tasks_status_created ON tasks(status, created_at);
CREATE TABLE IF NOT EXISTS events (
    seq INTEGER PRIMARY KEY AUTOINCREMENT,
    task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    data_json TEXT NOT NULL,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_events_task_seq ON events(task_id, seq);
CREATE TABLE IF NOT EXISTS app_settings (
    key TEXT PRIMARY KEY,
    value_json TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS session_locations (
    session_id TEXT PRIMARY KEY,
    cwd TEXT NOT NULL,
    source TEXT NOT NULL CHECK(source IN ('task','hermes')),
    discovered_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_session_locations_updated ON session_locations(updated_at DESC);
CREATE TABLE IF NOT EXISTS session_projects (
    session_id TEXT PRIMARY KEY,
    project_id TEXT,
    updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_session_projects_project ON session_projects(project_id);
CREATE TABLE IF NOT EXISTS deleted_sessions (
    session_id TEXT PRIMARY KEY,
    deleted_at TEXT NOT NULL
);
"""


def apply(conn):
    statements = [statement.strip() for statement in SCHEMA.split(";") if statement.strip()]
    # Legacy tables may lack indexed columns. Normalize them before indexes.
    for statement in statements:
        if statement.startswith("CREATE TABLE"):
            conn.execute(statement)
    columns = {row[1] for row in conn.execute("PRAGMA table_info(tasks)")}
    required = {"id", "prompt", "cwd", "status", "created_at", "updated_at"}
    if not required.issubset(columns):
        raise RuntimeError("Unsupported legacy tasks schema; migration requires the known Archon baseline")
    # The oldest supported task ledger contains only identity, cwd, status,
    # and timestamps. Optional execution/result fields did not exist yet.
    optional_columns = {
        "model": "TEXT", "provider": "TEXT",
        "skills_json": "TEXT NOT NULL DEFAULT '[]'",
        "result_json": "TEXT", "error": "TEXT",
        "started_at": "TEXT", "completed_at": "TEXT",
    }
    for name, declaration in optional_columns.items():
        if name not in columns:
            conn.execute(f"ALTER TABLE tasks ADD COLUMN {name} {declaration}")
    if "session_id" not in columns:
        conn.execute("ALTER TABLE tasks ADD COLUMN session_id TEXT")
    if "approval_mode" not in columns:
        conn.execute("ALTER TABLE tasks ADD COLUMN approval_mode TEXT NOT NULL DEFAULT 'approve'")
    if "chat_only" not in columns:
        conn.execute("ALTER TABLE tasks ADD COLUMN chat_only INTEGER NOT NULL DEFAULT 0")
    if "profile" not in columns:
        conn.execute("ALTER TABLE tasks ADD COLUMN profile TEXT")
    if "retry_at" not in columns:
        conn.execute("ALTER TABLE tasks ADD COLUMN retry_at TEXT")
    # Create this only after legacy tasks tables have gained session_id.
    conn.execute("CREATE INDEX IF NOT EXISTS idx_tasks_session_updated ON tasks(session_id, updated_at DESC, id DESC)")
    location_columns = {row[1] for row in conn.execute("PRAGMA table_info(session_locations)")}
    if "source" not in location_columns:
        conn.execute("ALTER TABLE session_locations ADD COLUMN source TEXT NOT NULL DEFAULT 'hermes'")
    if "discovered_at" not in location_columns:
        conn.execute("ALTER TABLE session_locations ADD COLUMN discovered_at TEXT NOT NULL DEFAULT ''")
    if "updated_at" not in location_columns:
        conn.execute("ALTER TABLE session_locations ADD COLUMN updated_at TEXT NOT NULL DEFAULT ''")
    # Sessions created before this registry existed already have their
    # dispatch directory in the task ledger. Seed the durable registry
    # once from those records, without overwriting a newer live mapping.
    conn.execute(
        """INSERT OR IGNORE INTO session_locations(session_id,cwd,source,discovered_at,updated_at)
           SELECT session_id,cwd,'task',created_at,updated_at
           FROM tasks
           WHERE NULLIF(TRIM(session_id),'') IS NOT NULL
             AND NULLIF(TRIM(cwd),'') IS NOT NULL
           ORDER BY created_at ASC"""
    )
    if "request_hash" not in columns:
        conn.execute("ALTER TABLE tasks ADD COLUMN request_hash TEXT")
    for statement in statements:
        if statement.startswith("CREATE INDEX"):
            conn.execute(statement)
