import { Check, DownloadSimple, FloppyDisk, UploadSimple } from '@phosphor-icons/react'
import { useRef, useState } from 'react'
import {
  APPEARANCE_DEFAULTS, appearanceForTheme, normalizeAppearance, readAppearance,
  saveAppearance, saveCustomAppearance, type AppearanceConfig,
} from '../lib/appearance'
import { applyTheme, readTheme, THEMES, type ThemeId } from '../lib/theme'
import { MARKS, MARK_IDS, MarkGlyph } from '../lib/marks'
import { BrandGlyph } from './BrandGlyph'

const UI_FONTS = [
  ['chivo','Chivo'],['schibsted','Schibsted'],['familjen','Familjen'],['epilogue','Epilogue'],['onest','Onest'],['gabarito','Gabarito'],['hanken','Hanken'],['be-vietnam','Be Vietnam'],['chakra-petch','Chakra Petch'],['rajdhani','Rajdhani'],['unbounded','Unbounded'],['martian-mono','Martian Mono'],['space-mono','Space Mono'],['plex-mono','Plex Mono'],['instrument-sans','Instrument Sans'],['dm-sans','DM Sans'],['plus-jakarta','Plus Jakarta'],['manrope','Manrope'],['figtree','Figtree'],['space-grotesk','Space Grotesk'],['ibm-plex-sans','IBM Plex Sans'],['archivo','Archivo'],['sora','Sora'],['outfit','Outfit'],['inter','Inter'],['system','System'],['jetbrains-mono','JetBrains Mono'],
] as const
const DISPLAY_FONTS = [
  ['playfair-black','Playfair Black'],['bodoni-black','Bodoni Black'],['prata','Prata'],['rozha','Rozha'],['yeseva','Yeseva'],['abril','Abril'],['suranna','Suranna'],['bellefair','Bellefair'],['cinzel','Cinzel'],['marcellus','Marcellus'],['italiana','Italiana'],['gloock','Gloock'],['eb-garamond','EB Garamond'],['young-serif','Young Serif'],['dm-serif','DM Serif'],['unicase','Unicase'],['anton','Anton'],['archivo-black','Archivo Black'],['antonio','Antonio'],['oswald','Oswald'],['big-shoulders','Big Shoulders'],['unbounded','Unbounded'],['cormorant','Cormorant'],['instrument-serif','Instrument Serif'],['playfair','Playfair'],['bodoni-moda','Bodoni Moda'],['baskerville','Baskerville'],['spectral','Spectral'],['newsreader','Newsreader'],['lora','Lora'],['syne','Syne'],['bricolage','Bricolage'],['space-grotesk','Space Grotesk'],['archivo','Archivo'],
] as const
const NOTES: Record<ThemeId,string> = { obsidian:'near-black, no chroma — light is the accent', indigo:'deep indigo ground, accent-400 line', carbon:'quieter blue-grey ground, blurple line', ivory:'paper ground, Cormorant over Lora', blueprint:'zero radius, Archivo, red accent', moss:'cooler dark, softer corners', ember:'warm dark for late nights' }
const METRICS: Array<{ key: keyof AppearanceConfig; label: string; min: number; max: number; step: number }> = [
  { key:'fontScale',label:'Type scale',min:.84,max:1.2,step:.01 },{ key:'fontWeight',label:'Interface weight',min:300,max:650,step:10 },{ key:'letterSpacing',label:'Letter spacing',min:-.04,max:.04,step:.002 },{ key:'iconScale',label:'Icon scale',min:.8,max:1.3,step:.01 },{ key:'iconStroke',label:'Icon weight',min:1,max:2.4,step:.1 },{ key:'density',label:'Density',min:.78,max:1.18,step:.01 },{ key:'radius',label:'Corner radius',min:0,max:24,step:1 },{ key:'blur',label:'Glass blur',min:0,max:36,step:1 },{ key:'sidebarWidth',label:'Sidebar width',min:190,max:380,step:2 },{ key:'composerWidth',label:'Composer width',min:520,max:1200,step:10 },
]

export function AppearanceStudio() {
  const [theme, setTheme] = useState<ThemeId>(readTheme())
  const [appearance, setAppearance] = useState<AppearanceConfig>(readAppearance())
  const [message, setMessage] = useState('')
  const importInput = useRef<HTMLInputElement>(null)
  const imageInput = useRef<HTMLInputElement>(null)
  const markInput = useRef<HTMLInputElement>(null)
  const commit = (next: AppearanceConfig, note = '') => { const safe = saveAppearance(normalizeAppearance(next)); setAppearance(safe); if (note) setMessage(note) }
  const update = <K extends keyof AppearanceConfig>(key: K, value: AppearanceConfig[K]) => commit({ ...appearance, [key]: value })
  const iconWeightLabel = appearance.iconStroke < 1.4 ? 'Thin icons' : appearance.iconStroke > 1.9 ? 'Bold icons' : 'Regular icons'
  const cycleIconWeight = () => update('iconStroke', appearance.iconStroke < 1.4 ? 1.55 : appearance.iconStroke < 1.9 ? 2.2 : 1.15)
  const chooseTheme = (id: ThemeId) => { setTheme(id); applyTheme(id); void window.archon?.setSettings({ theme: id }); commit(appearanceForTheme(id, appearance), `${THEMES.find((item) => item.id === id)?.name} applied`) }
  const exportTheme = () => { const href = URL.createObjectURL(new Blob([JSON.stringify({ version: 1, appearance }, null, 2)], { type:'application/json' })); const anchor = document.createElement('a'); anchor.href = href; anchor.download = 'archon-theme.json'; anchor.click(); URL.revokeObjectURL(href) }
  const importTheme = async (file?: File) => { if (!file) return; try { const value = JSON.parse(await file.text()); commit(normalizeAppearance(value.appearance || value), 'Custom theme imported') } catch { setMessage('That theme file is not valid') } }
  const fileDataUrl = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result || '')); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file) })
  const image = async (file?: File) => {
    if (!file || !file.type.startsWith('image/') || file.size > 10_000_000) { setMessage('Use a PNG, JPEG, or WebP under 10 MB'); return }
    try {
      const asset = await window.archon?.importAsset({ kind:'background', name:file.name, dataUrl:await fileDataUrl(file) })
      if (!asset) throw new Error('Background storage is unavailable')
      const current = readAppearance()
      const library = [asset, ...current.backgroundLibrary.filter((item) => item.id !== asset.id)].slice(0, 3)
      commit({ ...current, backgroundImage:asset.url, backgroundId:asset.id, backgroundLabel:asset.label, backgroundFile:asset.file, backgroundAddedAt:asset.addedAt, backgroundLibrary:library, useShippedBackground:false, backdropEnabled:true }, 'Background copied to the library')
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Background import failed') }
  }
  const markImage = async (file?: File) => {
    if (!file || !file.type.startsWith('image/') || file.size > 10_000_000) { setMessage('Use a PNG, JPEG, WebP, or SVG under 10 MB'); return }
    try {
      const asset = await window.archon?.importAsset({ kind:'mark', name:file.name, dataUrl:await fileDataUrl(file) })
      if (!asset) throw new Error('Mark storage is unavailable')
      commit({ ...readAppearance(), customMark:asset.url, customMarkFile:asset.file }, 'App mark copied to the brand library')
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Mark import failed') }
  }

  return <section className="appearance-studio reference-appearance">
    <div className="appearance-live-preview"><BrandGlyph/><b>ARCHON</b><div><span>Live preview — mark, wordmark and interface face as set below.</span><code>{theme[0].toUpperCase()+theme.slice(1)} · {UI_FONTS.find(([id]) => id === appearance.font)?.[1] || appearance.font} · {DISPLAY_FONTS.find(([id]) => id === appearance.displayFont)?.[1] || appearance.displayFont} · {appearance.customMark ? 'custom' : MARKS[appearance.mark].label.toLowerCase()}</code></div><button className="icon-weight-badge" onClick={cycleIconWeight}>{iconWeightLabel}</button><button onClick={() => commit({ ...appearance, font: appearanceForTheme(theme).font, displayFont: appearanceForTheme(theme).displayFont }, 'Following theme typography')}>Follow theme</button></div>

    <div className="appearance-row"><header><b>Theme</b><p>Seven grounds. Everything below overrides the one you pick.</p></header><div className="theme-reference-grid">{THEMES.map((item) => <button className={`theme-reference-tile ${item.id} ${theme === item.id ? 'selected' : ''}`} key={item.id} onClick={() => chooseTheme(item.id)}><span><b>{item.name}</b><i>{item.swatches.map((swatch) => <em key={swatch} style={{background:swatch}}/>)}</i></span><small>{NOTES[item.id]}</small></button>)}</div></div>

    <div className="appearance-row"><header><b>Interface face</b><p>Sidebar, sessions, tasks, settings — everything but the wordmark.</p></header><div className="font-reference-list">{UI_FONTS.map(([id,label]) => <button className={appearance.font === id ? 'selected' : ''} key={id} onClick={() => update('font', id)}><span>{label}</span>{appearance.font === id && <Check/>}</button>)}</div></div>
    <div className="appearance-row"><header><b>Display face</b><p>The wordmark only. Weight and tracking come with each pick.</p></header><div className="font-reference-list display">{DISPLAY_FONTS.map(([id,label]) => <button className={appearance.displayFont === id ? 'selected' : ''} key={id} onClick={() => update('displayFont', id)}><span>{label}</span>{appearance.displayFont === id && <Check/>}</button>)}</div></div>

    <div className="appearance-row"><header><b>Type colour</b><p>Interface ink, and the wordmark on its own.</p></header><div className="tone-controls"><small>Interface ink</small><div>{[['Theme',appearance.text],['Warm','#e8c49a'],['Cool','#9ab6e8'],['Tinted',appearance.accent],['Softer',appearance.muted]].map(([label,color]) => <button key={label} onClick={() => update('text',color)}><i style={{background:color}}/>{label}</button>)}</div><small>Wordmark</small><div>{([['tinted','Tinted',appearance.accent],['ink','Ink',appearance.text],['accent','Accent',appearance.accent],['ghost','Ghost',appearance.muted],['outline','Outline','transparent']] as const).map(([tone,label,color]) => <button className={appearance.wordmarkTone === tone ? 'selected' : ''} key={tone} onClick={() => update('wordmarkTone',tone)}><i style={{background:color}}/>{label}</button>)}</div></div></div>

    <div className="appearance-row"><header><b>App mark</b><p>Titlebar, replies, tray and packaging. Twenty-two, or your own.</p></header><div className="mark-reference-grid">{MARK_IDS.map((id) => <button className={!appearance.customMark && appearance.mark === id ? 'selected' : ''} key={id} onClick={() => commit({ ...appearance, mark:id, customMark:'', customMarkFile:'' })}><MarkGlyph mark={id}/><small>{MARKS[id].label}</small></button>)}<button className={appearance.customMark ? 'selected' : ''} onClick={() => markInput.current?.click()}><UploadSimple/><small>Upload</small></button></div></div>

    <div className="appearance-row"><header><b>Colour roles</b><p>Ground, surface, ink and accent for the current theme.</p></header><div className="colour-role-grid">{([['canvas','Ground'],['rail','Sidebar'],['surface','Surface'],['text','Ink'],['muted','Muted'],['accent','Accent']] as const).map(([key,label]) => <label key={key}><input type="color" value={appearance[key]} onChange={(event) => update(key,event.target.value)}/><span><b>{label}</b><code>{appearance[key].toUpperCase()}</code></span></label>)}</div></div>

    <div className="appearance-row"><header><b>Background</b><p>Saved plates live in the library — drop into a slot to keep one.</p></header><div className="background-reference"><div className="background-reference-grid"><button className={!appearance.useShippedBackground && !appearance.backgroundImage ? 'selected' : ''} onClick={() => commit({ ...appearance,backgroundImage:'',backgroundId:'',backgroundFile:'',useShippedBackground:false },'Background cleared')}><i className="none"/><small>None</small></button><button className={appearance.useShippedBackground && !appearance.backgroundImage ? 'selected' : ''} onClick={() => commit({ ...appearance,backgroundImage:'',backgroundId:'',backgroundFile:'',useShippedBackground:true,backdropEnabled:true },'Engraved ruins applied')}><i className="ruins"/><small>Engraved ruins</small></button>{[0,1,2].map((index) => { const asset = appearance.backgroundLibrary[index]; return <button key={asset?.id || `slot-${index}`} className={asset && appearance.backgroundId === asset.id ? 'selected' : ''} onClick={() => asset ? commit({ ...appearance,backgroundImage:asset.url,backgroundId:asset.id,backgroundLabel:asset.label,backgroundFile:asset.file,backgroundAddedAt:asset.addedAt,useShippedBackground:false,backdropEnabled:true },`${asset.label} applied`) : imageInput.current?.click()}><i className="slot" style={asset ? { backgroundImage:`url("${asset.url}")` } : undefined}>{asset ? '' : 'Drop'}</i><small>{asset?.label || `Saved ${index + 1}`}</small></button> })}</div><div className="background-options"><div>{([['cover','Fill'],['contain','Fit'],['tile','Tile']] as const).map(([id,label]) => <button className={appearance.backgroundFit === id ? 'active' : ''} key={id} onClick={() => update('backgroundFit',id)}>{label}</button>)}</div><label><span>Strength</span><input type="range" min="20" max="100" value={Math.round(appearance.backgroundDim*100)} onChange={(event) => update('backgroundDim',Number(event.target.value)/100)}/><code>{Math.round(appearance.backgroundDim*100)}%</code></label></div><code>{appearance.backgroundImage ? 'Device-local custom image' : appearance.useShippedBackground ? 'assets/home-backdrop.png' : 'No plate selected'}</code></div></div>

    <div className="appearance-row"><header><b>Surface</b><p>What the ground does behind the interface.</p></header><div className="surface-reference"><div>{(['none','halo','aurora','mesh','grid'] as const).map((pattern) => <button className={appearance.pattern === pattern ? 'active' : ''} key={pattern} onClick={() => update('pattern',pattern)}>{pattern[0].toUpperCase()+pattern.slice(1)}</button>)}</div><div className="surface-toggles"><article><span><b>Show background</b><small>Plate behind the start page</small></span><button className={`reference-switch ${appearance.backdropEnabled ? 'on' : ''}`} role="switch" aria-checked={appearance.backdropEnabled} aria-label="Toggle background effect" onClick={() => update('backdropEnabled',!appearance.backdropEnabled)}><i/></button></article><article><span><b>Glass surfaces</b><small>Blur panels over the ground</small></span><button className={`reference-switch ${appearance.glass ? 'on' : ''}`} role="switch" aria-checked={appearance.glass} onClick={() => update('glass',!appearance.glass)}><i/></button></article></div></div></div>

    <div className="appearance-row"><header><b>Metrics</b><p>Scale, spacing and motion. Reduced-motion from the OS always wins.</p></header><div className="metric-reference-grid">{METRICS.map((metric) => <label key={metric.key}><span>{metric.label}<code>{String(appearance[metric.key])}</code></span><input type="range" min={metric.min} max={metric.max} step={metric.step} value={Number(appearance[metric.key])} onChange={(event) => update(metric.key,Number(event.target.value) as never)}/></label>)}</div></div>

    <footer className="appearance-footer"><button onClick={() => commit(appearanceForTheme(theme,APPEARANCE_DEFAULTS),'Theme reset')}>Reset to theme</button><button onClick={() => importInput.current?.click()}><DownloadSimple/>Import JSON</button><button onClick={exportTheme}><UploadSimple/>Export JSON</button><button className="primary" onClick={() => { saveCustomAppearance(`Custom ${new Date().toLocaleDateString()}`, appearance); setMessage('Custom theme saved') }}><FloppyDisk/>Save as custom theme</button>{message && <span>{message}</span>}</footer>
    <input ref={imageInput} className="visually-hidden" type="file" accept="image/png,image/jpeg,image/webp" onChange={(event) => void image(event.target.files?.[0])}/><input ref={markInput} className="visually-hidden" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" onChange={(event) => void markImage(event.target.files?.[0])}/><input ref={importInput} className="visually-hidden" type="file" accept="application/json,.json" onChange={(event) => void importTheme(event.target.files?.[0])}/>
  </section>
}
