export type ConnectionConfig = { serverUrl: string; token: string; secureStorage?: boolean }
export type TaskStatus = 'queued' | 'running' | 'completed' | 'failed' | 'cancelled' | 'blocked'
export type Task = { id: string; prompt: string; cwd?: string; model?: string; provider?: string; session_id?: string; approval_mode?: 'auto' | 'approve' | 'plan'; chat_only?: boolean; skills: string[]; status: TaskStatus; result?: { text?: string }; error?: string; created_at: string; started_at?: string; updated_at: string }
export type TaskEvent = { seq: number; task_id?: string; type: string; data: Record<string, unknown>; created_at?: string }
export type Skill = { name: string; description: string; category: string; path: string; enabled: boolean; content?: string }
export type FileItem = { name: string; path: string; is_dir: boolean; restricted: boolean; size: number; modified_at: string; mime?: string }
export type Backup = { id: string; created_at: string; plain_path?: string; encrypted_path?: string; plain_size?: number; encrypted_size?: number; encrypted: boolean }
export type CronJob = { id: string; name: string; enabled: boolean; state?: string; schedule: string; next_run_at?: string; last_run_at?: string; last_status?: string; last_error?: string; deliver?: string; prompt?: string; model?: string; provider?: string }
export type TerminalSession = { name: string; label?: string; windows?: number; created_at_epoch?: number; cwd?: string; persistent: boolean }
export type Project = { id: string; slug: string; name: string; description: string; icon: string; color: string; primary_path: string; folders: Array<{ path: string; label?: string; is_primary: boolean }> }
export type PrimeSession = { id: string; source: string; title: string; model: string; cwd: string; project_id?: string; started_at: string | number; last_active: string | number; message_count: number; active: boolean; preview: string }
export type ChatMessage = { id: number; role: 'user' | 'assistant'; content: string; timestamp: string | number }
export type ModelProvider = { id: string; models: string[] }
export type ModelCatalog = { current: { provider?: string; model?: string }; fallback?: unknown; providers: ModelProvider[]; choices: Array<{ provider: string; model: string }> }
export type LogEntry = { id: string; timestamp: string; level: 'DEBUG' | 'INFO' | 'WARNING' | 'ERROR' | 'CRITICAL'; source: string; component: string; message: string }
export type VoiceStatus = { available: boolean; stt: { available: boolean; provider: string }; tts: { available: boolean; provider: string } }
export type TranscriptionResult = { success: boolean; transcript: string; provider: string }
export type SpeechResult = { success: boolean; data_url: string; provider: string }
