import React from 'react'
import ReactDOM from 'react-dom/client'
import '@fontsource-variable/inter'
import '@fontsource-variable/chivo'
import '@fontsource-variable/playfair-display'
import '@fontsource-variable/archivo'
import '@fontsource-variable/cormorant-garamond'
import '@fontsource-variable/lora'
import '@xterm/xterm/css/xterm.css'
import './styles.css'
import './v2.css'
import './canonical-v2.css'
import { App } from './App'
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>)
