// Local integration harness: the actual patched v0.3.0 renderer, disposable I/O.
// node current/testing/preview.cjs /path/to/official.asar
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http');
const {patchRenderer,verifyOfficial,prepareCollaboration}=require('../candidate.cjs');const asar=require('@electron/asar');const baseline=require('../baseline.json');
const input=process.argv[2];verifyOfficial(fs.readFileSync(input));const root=fs.mkdtempSync(path.join(os.tmpdir(),'archon-ide-ui-'));asar.extractAll(input,root);
prepareCollaboration(root);
const renderer=path.join(root,'dist/renderer');fs.writeFileSync(path.join(root,baseline.rendererPath),patchRenderer(fs.readFileSync(path.join(root,baseline.rendererPath),'utf8')));
let html=fs.readFileSync(path.join(renderer,'index.html'),'utf8');html=html.replace('<script type="module"','<script src="/test-bridge.js"></script><script type="module"');fs.writeFileSync(path.join(renderer,'index.html'),html);
const files=new Map([['/workspace/src/app.ts','export function greet(name: string) {\n  return `Hello, ${name}!`;\n}\n'],['/workspace/src/long.ts',Array.from({length:120},(_,i)=>'// Line '+(i+1)+' — code stays aligned when scrolling').join('\n')],['/workspace/src/partial.txt','partial content'],['/workspace/src/fail.ts','failed file'],['/workspace/README.md','# Test workspace\n']]);let writes=[];
const sessions=[{id:'audit-one',title:'Build greeting · UI test',cwd:'/workspace',source:'prime-cli',message_count:3,last_active:Date.now()/1000},{id:'audit-two',title:'Other task · isolation test',cwd:'/workspace',source:'prime-cli',message_count:2,last_active:Date.now()/1000-10}];
const reply='Created [app.ts](src/app.ts:1).\n\n```typescript filename="app.ts"\nexport function greet(name: string) {\n  return `Hello, ${name}!`;\n}\n```\n\nPreview: http://127.0.0.1:4318/result\n';
sessions.forEach(s=>{s.project_id='audit-project'});
const noop='()=>{}';
const bridge=`let td=()=>{},ts=()=>{};const terminal={onData:f=>{td=f;return()=>{td=()=>{}}},onStatus:f=>{ts=f;return()=>{ts=()=>{}}},connect:async()=>{ts(true);td('Disposable terminal ready\\n$ ')},disconnect:async()=>{},resize:async()=>{},send:async text=>td(text+'UI terminal command received\\n$ ')};const off=()=>()=>{};const webListeners=new Set();let webState={id:'browser',url:'',title:'',loading:false,canGoBack:false,canGoForward:false,error:null},history=[],position=-1,frame;
const notify=()=>webListeners.forEach(f=>f({...webState}));
const navigate=(id,url)=>{try{url=new URL(url.includes('://')?url:'https://'+url).href}catch{return}history=history.slice(0,position+1);history.push(url);position++;show(url)};
const show=url=>{webState={...webState,url,canGoBack:position>0,canGoForward:position<history.length-1};if(frame)frame.src=url;notify()};
window.archon={terminal,settings:{read:async()=>({serverUrl:'http://127.0.0.1:4318',defaultCwd:'/workspace',theme:'dark'}),patch:async()=>{}},api:{configure:async()=>{},configureV2Workspace:()=>{},onEvent:off,onV2Event:off,onStatus:off,call:async(op,payload)=>{const r=await fetch('/bridge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({op,payload})});if(!r.ok)throw Error(await r.text());return r.json()}},token:{present:async()=>true},assets:{read:async()=>null},clipboard:{writeText:text=>navigator.clipboard.writeText(text)},window:{minimize:()=>{},maximize:()=>{},close:()=>{}},openExternal:url=>window.open(url,'_blank'),web:{onState:f=>{webListeners.add(f);queueMicrotask(notify);return()=>webListeners.delete(f)},navigate,back:()=>{if(position>0)show(history[--position])},forward:()=>{if(position<history.length-1)show(history[++position])},reload:()=>{if(frame)frame.src=webState.url;notify()},stop:()=>{},hide:()=>{if(frame)frame.style.display='none'},setBounds:(id,b,visible)=>{if(!frame){frame=document.createElement('iframe');frame.title='Test browser surface';frame.style.cssText='position:fixed;border:0;z-index:9;background:#171717';document.body.append(frame)}Object.assign(frame.style,{left:b.x+'px',top:b.y+'px',width:b.width+'px',height:b.height+'px',display:visible?'block':'none'});if(webState.url&&!frame.src)frame.src=webState.url},renderHtml:()=>{},capture:async()=>null}};
const originalCall=window.archon.api.call;window.archon.api.call=(op,payload)=>op==='projects'?Promise.resolve([{id:'audit-project',name:'Greeting project',primary_path:'/workspace'}]):originalCall(op,payload);
window.addEventListener('error',e=>fetch('/ui-error',{method:'POST',body:e.message}));window.addEventListener('unhandledrejection',e=>fetch('/ui-error',{method:'POST',body:String(e.reason)}));
`;
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname==='/ui-error'){let body='';for await(const c of req)body+=c;console.error('UI ERROR',body);res.end();return}
if(url.pathname==='/test-bridge.js'){res.setHeader('Content-Type','text/javascript');res.end(bridge);return}
if(url.pathname==='/result'){res.setHeader('Content-Type','text/html');res.end('<h1>Greeting preview</h1><p>Hello, Archon!</p><a href="/result-two">Next page</a>');return}
if(url.pathname==='/result-two'){res.setHeader('Content-Type','text/html');res.end('<h1>Second preview page</h1>');return}
if(url.pathname==='/evidence'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({writes,files:[...files],root}));return}
if(url.pathname==='/bridge'){let body='';for await(const c of req)body+=c;const {op,payload:p={}}=JSON.parse(body);let data=[];try{switch(op){case 'health':data={ok:true,version:'0.3.0'};break;case 'status':data={hostname:'DISPOSABLE UI TEST',uptime:1};break;case 'sessions':data=sessions;break;case 'messages':data=p.sessionId==='audit-two'?[{id:'other',role:'assistant',content:'```python\nprint("Other session only")\n```'}]:[{id:'request',role:'user',content:'Write a greeting function.'},{id:'write',role:'assistant',kind:'tool',content:'write_file\n'+JSON.stringify({path:'src/app.ts',content:files.get('/workspace/src/app.ts')})},{id:'reply',role:'assistant',content:reply}];break;case 'files':{let folder=p.path==='.'?'/workspace':p.path.replace(/\/$/,'');data=[...new Set([...files.keys()].filter(x=>x.startsWith(folder+'/')).map(x=>x.slice(folder.length+1).split('/')[0]))].map(name=>({name,path:folder+'/'+name,is_dir:!files.has(folder+'/'+name)}));if(folder==='/workspace/src')data.push({name:'.env',path:'/workspace/src/.env',is_dir:false,restricted:true});break}case 'fileRead':if(p.path.endsWith('fail.ts'))throw Error('Simulated read failure');if(!files.has(p.path))throw Error('Missing test file');data={content:files.get(p.path),truncated:p.path.endsWith('partial.txt'),binary:false};break;case 'fileWrite':if(!files.has(p.path)||p.path.endsWith('partial.txt')||p.path.endsWith('fail.ts'))throw Error('Write not allowed');files.set(p.path,p.content);writes.push({path:p.path,content:p.content});data={ok:true};break;case 'terminalList':data=[];break;case 'terminalCreate':data={name:'test-terminal',cwd:'/workspace'};break;case 'terminalRead':data={output:'Disposable terminal\n$ ',cursor:1};break;default:break}res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data));}catch(e){res.statusCode=400;res.end(e.message)}return}
let file=path.resolve(renderer,'.'+(url.pathname==='/'?'/index.html':url.pathname));if(!file.startsWith(renderer+'/')){res.statusCode=403;res.end();return}try{res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.statusCode=404;res.end('Not found')}});
server.listen(4318,'127.0.0.1',()=>console.log('Disposable candidate UI: http://127.0.0.1:4318\n'+root));
